export { default as Bear } from './bear';
export { default as Elephant } from './elephant';
export { default as Fox } from './fox';
export { default as Giraffe } from './giraffe';
export { default as Hippo } from './hippo';
export { default as Lion } from './lion';
export { default as Sloth } from './sloth';
export { default as Tiger } from './tiger';
export { default as Zebra } from './zebra';
